{% set name = "pynrrd" %}
{% set version = "0.4.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 74a8024065393f4af11163b7aad33a368abed5ef2c535ef7a7e700e2335ebf6f

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - numpy>=1.11.1
    - pip
    - python
  run:
    - {{ pin_compatible("numpy") }}
    - python

test:
  imports:
    - nrrd

about:
  home: "https://github.com/mhe/pynrrd"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Pure python module for reading and writing NRRD files."
  doc_url: https://pynrrd.readthedocs.io
  dev_url: https://github.com/mhe/pynrrd

extra:
  recipe-maintainers:
    - bhoeckendorf
